Repository WarnerMedia/artemis, pull requests merged in 2024-09, with the labels that each got.

#259 Update ruff to 0.6.4
  backend/Pipfile
  backend/Pipfile.lock
  orchestrator/Pipfile
  orchestrator/Pipfile.lock
Labels: dependencies

#264 Update terraform aws provider to v5.66.0
  backend/terraform/environments/example/main.tf
  backend/terraform/modules/analyzer/db_cleanup.tf
  backend/terraform/modules/analyzer/lambdas.tf
  backend/terraform/modules/analyzer/license_retriever.tf
  backend/terraform/modules/analyzer/reports.tf
  backend/terraform/modules/analyzer/scan_scheduler.tf
  backend/terraform/modules/analyzer/update_github_org_users.tf
  backend/terraform/modules/analyzer/variables.tf
  orchestrator/terraform/modules/heimdall/lambda_networking.tf
  orchestrator/terraform/modules/heimdall/lambdas.tf
  orchestrator/terraform/modules/heimdall/s3.tf
  ui/terraform/modules/analyzer-ui/s3.tf
Labels: dependencies

#265 Update python dependencies
  backend/Pipfile
  backend/Pipfile.lock
  orchestrator/Pipfile
  orchestrator/Pipfile.lock
Labels: dependencies

#263 Remove the rds-aurora terraform module
  backend/terraform/modules/analyzer/db.tf
  backend/terraform/modules/analyzer/secrets.tf
Labels: dependencies

#266 Update Lamba & s3 configurations
  backend/lambdas/maintenance/license_retriever/license_retriever/retrievers/gem.py
  backend/lambdas/maintenance/license_retriever/license_retriever/retrievers/npm.py
  backend/terraform/modules/analyzer/audit_log.tf
  backend/terraform/modules/analyzer/event_stream.tf
  backend/terraform/modules/analyzer/lambdas.tf
  backend/terraform/modules/analyzer/license_retriever.tf
  backend/terraform/modules/analyzer/messaging.tf
  backend/terraform/modules/analyzer/modules/engine_cluster/main.tf
  backend/terraform/modules/analyzer/scan_scheduler.tf
  backend/terraform/modules/metadata_events/main.tf
  backend/terraform/modules/s3/main.tf
  backend/terraform/modules/secrets_management/main.tf
  orchestrator/terraform/modules/heimdall/lambdas.tf
  orchestrator/terraform/modules/heimdall/s3.tf
Labels: bug, dependencies

#281 Fix bug in trivy_sbom
  backend/engine/plugins/trivy_sbom/parser.py
  backend/engine/tests/test_trivy_sbom.py
Labels: bug
